
DROP TABLE RISGAP.RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE CASCADE CONSTRAINTS;

CREATE TABLE RISGAP.RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE 
   (ID                                  NUMBER(10)  ,
   RAW_PAYLOAD                          CLOB        ,
   STATUS                               VARCHAR2(1) ,
   PARTITION_ID                         NUMBER(10)  ,
   OFFSET_ID                            NUMBER(20)  ,
   CRT_USER                             VARCHAR2(30),
   CRT_DTTM                             TIMESTAMP(6),
   UPD_USER                             VARCHAR2(30),
   UPD_DTTM                             TIMESTAMP(6)
  )
  PARTITION BY HASH (ID)
(  
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_1,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_2,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_3,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_4,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_5,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_6,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_7,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_8,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_9,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_10,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_11,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_12,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_13,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_14,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_15,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_16,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_17,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_18,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_19,
   PARTITION RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE_20
)
TABLESPACE RISGAP_DATA;

CREATE OR REPLACE PUBLIC SYNONYM RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE FOR RISGAP.RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE;

GRANT SELECT ON RISGAP.RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE TO RISUSER_READONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON RISGAP.RIS_ISOR_GAP_KAFKA_OUTBOUND_STAGE TO RISGAP,RISUSER;



DROP TABLE RISGAP.RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE CASCADE CONSTRAINTS;

CREATE TABLE RISGAP.RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE 
   (ID                                  NUMBER(10)  ,
   RAW_PAYLOAD                          CLOB        ,
   STATUS                               VARCHAR2(1) ,
   PARTITION_ID                         NUMBER(10)  ,
   OFFSET_ID                            NUMBER(20)  ,
   CRT_USER                             VARCHAR2(30),
   CRT_DTTM                             TIMESTAMP(6),
   UPD_USER                             VARCHAR2(30),
   UPD_DTTM                             TIMESTAMP(6)
  )
  PARTITION BY HASH (ID)
(  
   PARTITION RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE_1,
   PARTITION RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE_2,
   PARTITION RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE_3,
   PARTITION RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE_4,
   PARTITION RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE_5,
   PARTITION RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE_6,
   PARTITION RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE_7,
   PARTITION RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE_8,
   PARTITION RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE_9,
   PARTITION RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE_10
)
TABLESPACE RISGAP_DATA;

CREATE OR REPLACE PUBLIC SYNONYM RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE FOR RISGAP.RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE;

GRANT SELECT ON RISGAP.RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE TO RISUSER_READONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON RISGAP.RIS_ISOR_GAPOUT_KAFKA_OUTBOUND_STAGE TO RISGAP,RISUSER;

DROP TABLE RISGAP.RIS_ISOR_NRC_KAFKA_OUTBOUND_STAGE CASCADE CONSTRAINTS;

CREATE TABLE RISGAP.RIS_ISOR_NRC_KAFKA_OUTBOUND_STAGE 
   (ID                                  NUMBER(10)  ,
   RAW_PAYLOAD                          CLOB        ,
   STATUS                               VARCHAR2(1) ,
   PARTITION_ID                         NUMBER(10)  ,
   OFFSET_ID                            NUMBER(20)  ,
   CRT_USER                             VARCHAR2(30),
   CRT_DTTM                             TIMESTAMP(6),
   UPD_USER                             VARCHAR2(30),
   UPD_DTTM                             TIMESTAMP(6)
  )
  PARTITION BY HASH (ID)
(  
   PARTITION RIS_ISOR_NRC_KAFKA_OUTBOUND_STAGE_1,
   PARTITION RIS_ISOR_NRC_KAFKA_OUTBOUND_STAGE_2
)
TABLESPACE RISGAP_DATA;

CREATE OR REPLACE PUBLIC SYNONYM RIS_ISOR_NRC_KAFKA_OUTBOUND_STAGE FOR RISGAP.RIS_ISOR_NRC_KAFKA_OUTBOUND_STAGE;

GRANT SELECT ON RISGAP.RIS_ISOR_NRC_KAFKA_OUTBOUND_STAGE TO RISUSER_READONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON RISGAP.RIS_ISOR_NRC_KAFKA_OUTBOUND_STAGE TO RISGAP,RISUSER;

DROP TABLE RISGAP.RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE CASCADE CONSTRAINTS;

CREATE TABLE RISGAP.RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE 
   (ID                                  NUMBER(10)  ,
   RAW_PAYLOAD                          CLOB        ,
   STATUS                               VARCHAR2(1) ,
   PARTITION_ID                         NUMBER(10)  ,
   OFFSET_ID                            NUMBER(20)  ,
   CRT_USER                             VARCHAR2(30),
   CRT_DTTM                             TIMESTAMP(6),
   UPD_USER                             VARCHAR2(30),
   UPD_DTTM                             TIMESTAMP(6)
  )
  PARTITION BY HASH (ID)
(  
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_1,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_2,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_3,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_4,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_5,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_6,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_7,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_8,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_9,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_10,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_11,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_12,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_13,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_14,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_15,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_16,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_17,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_18,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_19,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_20,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_21,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_22,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_23,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_24,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_25,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_26,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_27,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_28,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_29,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_30,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_31,
   PARTITION RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE_32
)
TABLESPACE RISGAP_DATA;

CREATE OR REPLACE PUBLIC SYNONYM RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE FOR RISGAP.RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE;

GRANT SELECT ON RISGAP.RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE TO RISUSER_READONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON RISGAP.RIS_ISOR_ON_KAFKA_OUTBOUND_STAGE TO RISGAP,RISUSER;


DROP TABLE RISGAP.RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE CASCADE CONSTRAINTS;

CREATE TABLE RISGAP.RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE 
   (ID                                  NUMBER(10)  ,
   RAW_PAYLOAD                          CLOB        ,
   STATUS                               VARCHAR2(1) ,
   PARTITION_ID                         NUMBER(10)  ,
   OFFSET_ID                            NUMBER(20)  ,
   CRT_USER                             VARCHAR2(30),
   CRT_DTTM                             TIMESTAMP(6),
   UPD_USER                             VARCHAR2(30),
   UPD_DTTM                             TIMESTAMP(6)
  )
  PARTITION BY HASH (ID)
(  
   PARTITION RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE_1,
   PARTITION RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE_2,
   PARTITION RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE_3,
   PARTITION RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE_4,
   PARTITION RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE_5,
   PARTITION RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE_6,
   PARTITION RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE_7,
   PARTITION RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE_8
)
TABLESPACE RISGAP_DATA;

CREATE OR REPLACE PUBLIC SYNONYM RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE FOR RISGAP.RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE;

GRANT SELECT ON RISGAP.RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE TO RISUSER_READONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON RISGAP.RIS_ISOR_BRFS_KAFKA_OUTBOUND_STAGE TO RISGAP,RISUSER;


DROP TABLE RISGAP.RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE CASCADE CONSTRAINTS;

CREATE TABLE RISGAP.RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE 
   (ID                                  NUMBER(10)  ,
   RAW_PAYLOAD                          CLOB        ,
   STATUS                               VARCHAR2(1) ,
   PARTITION_ID                         NUMBER(10)  ,
   OFFSET_ID                            NUMBER(20)  ,
   CRT_USER                             VARCHAR2(30),
   CRT_DTTM                             TIMESTAMP(6),
   UPD_USER                             VARCHAR2(30),
   UPD_DTTM                             TIMESTAMP(6)
  )
  PARTITION BY HASH (ID)
(  
   PARTITION RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE_STAGE_1,
   PARTITION RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE_STAGE_2,
   PARTITION RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE_STAGE_3,
   PARTITION RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE_STAGE_4,
   PARTITION RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE_STAGE_5,
   PARTITION RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE_STAGE_6,
   PARTITION RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE_STAGE_7,
   PARTITION RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE_STAGE_8
)
TABLESPACE RISGAP_DATA;

CREATE OR REPLACE PUBLIC SYNONYM RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE FOR RISGAP.RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE;

GRANT SELECT ON RISGAP.RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE TO RISUSER_READONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON RISGAP.RIS_ISOR_BR_KAFKA_OUTBOUND_STAGE TO RISGAP,RISUSER;

DROP TABLE RISGAP.RIS_ISOR_ATHLETA_KAFKA_OUTBOUND_STAGE CASCADE CONSTRAINTS;

CREATE TABLE RISGAP.RIS_ISOR_ATHLETA_KAFKA_OUTBOUND_STAGE 
   (ID                                  NUMBER(10)  ,
   RAW_PAYLOAD                          CLOB        ,
   STATUS                               VARCHAR2(1) ,
   PARTITION_ID                         NUMBER(10)  ,
   OFFSET_ID                            NUMBER(20)  ,
   CRT_USER                             VARCHAR2(30),
   CRT_DTTM                             TIMESTAMP(6),
   UPD_USER                             VARCHAR2(30),
   UPD_DTTM                             TIMESTAMP(6)
  )
TABLESPACE RISGAP_DATA;

CREATE OR REPLACE PUBLIC SYNONYM RIS_ISOR_ATHLETA_KAFKA_OUTBOUND_STAGE FOR RISGAP.RIS_ISOR_ATHLETA_KAFKA_OUTBOUND_STAGE;

GRANT SELECT ON RISGAP.RIS_ISOR_ATHLETA_KAFKA_OUTBOUND_STAGE TO RISUSER_READONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON RISGAP.RIS_ISOR_ATHLETA_KAFKA_OUTBOUND_STAGE TO RISGAP,RISUSER;



